apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: portfolio
resources:
  - 10-qdrant.yaml
  - 15-llm-router.yaml
  - 16-redis.yaml
  - 20-smartdoc-backend.yaml
  - 25-smartdoc-agent.yaml
  - 30-smartdoc-frontend.yaml
